### ISSUE TITLE
Improved support for Kubernetes roles

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1819]
This epic tracks sub-issues that make discovering, granting Kubernetes roles easier and safer for users

**Issues**
- [ ] https://github.com/infrahq/infra/issues/1817
- [ ] https://github.com/infrahq/infra/issues/1818
- [ ] https://github.com/infrahq/infra/issues/90
