### ISSUE TITLE
Simpler grants

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1824]
Grants today have quite a few rough edges - this epic tracks making them a safer and simpler experience for users

- [ ] https://github.com/infrahq/infra/issues/1822
- [ ] https://github.com/infrahq/infra/issues/1823
- [ ] https://github.com/infrahq/infra/issues/1787
