### ISSUE TITLE
ui: updated list views & side panel

### ISSUE THREAD

**Issue by jmorganca** [infrahq/infra#1844]
update: https://www.figma.com/file/RD3lsWESwo1QykjaT4IB7y/UI-Milestone-1?node-id=895%3A4833

- [x] signup / login page #1915 
- [ ] infrastructure page  & add cluster page #1917 
- [x] move the share dialog to the side panel #1918 
- [x] empty state #1919 
- [ ] provider page #1916
