### ISSUE TITLE
ui: unit testing for components and pages

### ISSUE THREAD

**Issue by hoyyeva** [infrahq/infra#2511]
- [x] unit test setup, components: `<Badge />`, `<ComboboxItem />` `<EmptyData />`, login page - (https://github.com/infrahq/infra/pull/2624)
- [x] components: `<DeleteModal />`, `<EmptyTable />`, `<ErrorMessage />`, `<PageHeader />`, `<Metadata />`  (https://github.com/infrahq/infra/pull/2656)
- [ ] components: layouts
- [ ] components: `<GrantForm />`, `<GrantsList />`, `<RoleSelect />`
- [ ] components: `<HeaderIcon />`, `<IdentityList />`,` <TypeaheadCombobox />`
- [x] components: `<Notification />`, `<RemoveButton />` ,` <ProfileIcon />` (https://github.com/infrahq/infra/pull/2690)
- [ ] pages: signup
- [ ] pages: groups
- [ ] pages: users
- [ ] pages: destinations
- [ ] pages: settings / logout
