### ISSUE TITLE
Replace remaining uses of go-playground/validator

### ISSUE THREAD

**Issue by dnephin** [infrahq/infra#2583]
When #1763 is complete all `api` request structs will be using `internal/validate` and we'll be able to remove the static `pgValidate` variable from the `internal/server` package.

This issue is to replace other uses of `go-playground/validator` with `internal/validate`.

* [x] `server/config.go` #2612
* [x] `data/migrations.go` - there was only one, so bundled it with #2611
* [x] `server/migrations.go` - removed in #2604
* [x] `models/*` - should be removed along with gorm #2659
* [x] `providers/oidc.go` - #2611

For any of these that only use `require`, we may be better off with a simple `if v.Field != ""` instead of using a validation library. I believe `models` should only use `require`.
