### ISSUE TITLE
security: remove all non-test uses of InsecureSkipVerify

### ISSUE THREAD

**Issue by ssoroka** [infrahq/infra#296]
InsecureSkipVerify is pretty dangerous. It allows someone to [MITM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) the connection, pretend to be a host or client, and undermine all security.

It should never be a default, and we should probably just not allow it; solving whatever problems that creates.

Places we do this:
- [x] Connector <> Server connection #2485
- [x] CLI <> Server login #1541
- [ ] update the quickstart docs to remove reference to skip-tls-verify #2638

**Comment by dnephin** [comment]
#1541 addresses CLI -> server. That trust can be established by either a prompt, or by allowing the user to specify the cert with a command line flag.

That leaves connector -> server. A command line flag on the connector would let us pass the trusted CA to the connector, instead of using `--skip-tls-verify`.
